# Generated by Django 3.2.4 on 2021-07-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.PositiveBigIntegerField(default=0, null=True, unique=True),
        ),
    ]
