# Generated by Django 3.2.4 on 2021-07-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='exp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
