# Generated by Django 3.2.4 on 2021-07-17 14:56

from django.db import migrations
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', login.models.UserManager()),
            ],
        ),
    ]
