# Generated by Django 3.2.4 on 2021-07-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_user_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='exp',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
