# Generated by Django 3.2.4 on 2021-07-27 06:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_user_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='exp',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
