# Generated by Django 3.2.4 on 2021-07-27 05:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=50)),
                ('minprice', models.IntegerField()),
                ('price_desc', models.ImageField(blank=True, null=True, upload_to='')),
                ('profile', models.ImageField(blank=True, null=True, upload_to='')),
                ('kakaourl', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('shop_type', models.IntegerField(choices=[(0, 'studio'), (1, 'beautyshop')])),
                ('like_users', models.ManyToManyField(related_name='like_shops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
