# Generated by Django 3.2.4 on 2021-07-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='affiliates',
            field=models.ManyToManyField(blank=True, null=True, related_name='_shop_shop_affiliates_+', to='shop.Shop'),
        ),
    ]
