# Generated by Django 3.2.4 on 2021-08-02 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='profile_1',
            new_name='profile',
        ),
    ]
